title: Hello, world! I'm Ahmet ATAY
description: > # this means to ignore newlines until "baseurl:"
  I am a web developer focused on backend-end development / Electronic music lover and founder of themixzone.com / Chess enthusiast and WingChun fighter.
# permalink: ':title/'
permalink: /:categories/:year/:month/:day/:title:output_ext
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Ahmet ATAY # add your name
author-img: ahmet-atay.jpg # add your photo
about-author: I am a web developer focused on backend-end development / Electronic music lover and founder of themixzone.com / Chess enthusiast and WingChun fighter.
social-twitter: atayahmett
social-facebook: # add your Facebook handle
social-github: atayahmet # add your Github handle
social-linkedin: ahmet-atay-48688a53
social-email: ahmet.atay@hotmail.com

# Disqus
discus-identifier: atayahmet # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
